# **Import Libraries & Load Data**

In [1]:
import pandas as pd

df = pd.read_csv("/content/ambient_temperature_system_failure.csv")
df['timestamp'] = pd.to_datetime(df['timestamp'])
df.head()

            timestamp      value
0 2013-07-04 00:00:00  69.880835
1 2013-07-04 01:00:00  71.220227
2 2013-07-04 02:00:00  70.877805
3 2013-07-04 03:00:00  68.959400
4 2013-07-04 04:00:00  69.283551

# **Rolling Average Feature**

In [2]:
df['rolling_avg_24h'] = df['value'].rolling(window=24).mean()
df.head(30)

             timestamp      value  rolling_avg_24h
0  2013-07-04 00:00:00  69.880835              NaN
1  2013-07-04 01:00:00  71.220227              NaN
2  2013-07-04 02:00:00  70.877805              NaN
3  2013-07-04 03:00:00  68.959400              NaN
4  2013-07-04 04:00:00  69.283551              NaN
5  2013-07-04 05:00:00  70.060966              NaN
6  2013-07-04 06:00:00  69.279765              NaN
7  2013-07-04 07:00:00  69.369608              NaN
8  2013-07-04 08:00:00  69.166714              NaN
9  2013-07-04 09:00:00  68.986083              NaN
10 2013-07-04 10:00:00  69.965062              NaN
11 2013-07-04 11:00:00  70.556195              NaN
12 2013-07-04 12:00:00  70.307505              NaN
13 2013-07-04 13:00:00  70.246252              NaN
14 2013-07-04 14:00:00  69.854908              NaN
15 2013-07-04 15:00:00  71.643291              NaN
16 2013-07-04 16:00:00  71.245659              NaN
17 2013-07-04 17:00:00  70.745100              NaN
18 2013-07-04 18:00:00  71.373298              NaN
19 2013-07-04 19:00:00  71.795751              NaN
20 2013-07-04 20:00:00  72.091606              NaN
21 2013-07-04 21:00:00  71.553076              NaN
22 2013-07-04 22:00:00  72.187695              NaN
23 2013-07-04 23:00:00  70.649957        70.470846
24 2013-07-05 00:00:00  71.342742        70.531759
25 2013-07-05 01:00:00  71.586728        70.547030
26 2013-07-05 02:00:00  70.977001        70.551163
27 2013-07-05 03:00:00  70.243882        70.604683
28 2013-07-05 04:00:00  70.432826        70.652570
29 2013-07-05 05:00:00  69.748963        70.639570

# **Rolling Standard Deviation Feature**

In [3]:
df['rolling_std_24h'] = df['value'].rolling(window=24).std()
df.head(30)

             timestamp      value  rolling_avg_24h  rolling_std_24h
0  2013-07-04 00:00:00  69.880835              NaN              NaN
1  2013-07-04 01:00:00  71.220227              NaN              NaN
2  2013-07-04 02:00:00  70.877805              NaN              NaN
3  2013-07-04 03:00:00  68.959400              NaN              NaN
4  2013-07-04 04:00:00  69.283551              NaN              NaN
5  2013-07-04 05:00:00  70.060966              NaN              NaN
6  2013-07-04 06:00:00  69.279765              NaN              NaN
7  2013-07-04 07:00:00  69.369608              NaN              NaN
8  2013-07-04 08:00:00  69.166714              NaN              NaN
9  2013-07-04 09:00:00  68.986083              NaN              NaN
10 2013-07-04 10:00:00  69.965062              NaN              NaN
11 2013-07-04 11:00:00  70.556195              NaN              NaN
12 2013-07-04 12:00:00  70.307505              NaN              NaN
13 2013-07-04 13:00:00  70.246252              NaN              NaN
14 2013-07-04 14:00:00  69.854908              NaN              NaN
15 2013-07-04 15:00:00  71.643291              NaN              NaN
16 2013-07-04 16:00:00  71.245659              NaN              NaN
17 2013-07-04 17:00:00  70.745100              NaN              NaN
18 2013-07-04 18:00:00  71.373298              NaN              NaN
19 2013-07-04 19:00:00  71.795751              NaN              NaN
20 2013-07-04 20:00:00  72.091606              NaN              NaN
21 2013-07-04 21:00:00  71.553076              NaN              NaN
22 2013-07-04 22:00:00  72.187695              NaN              NaN
23 2013-07-04 23:00:00  70.649957        70.470846         1.012776
24 2013-07-05 00:00:00  71.342742        70.531759         1.019686
25 2013-07-05 01:00:00  71.586728        70.547030         1.033101
26 2013-07-05 02:00:00  70.977001        70.551163         1.034679
27 2013-07-05 03:00:00  70.243882        70.604683         0.980569
28 2013-07-05 04:00:00  70.432826        70.652570         0.940490
29 2013-07-05 05:00:00  69.748963        70.639570         0.951119

# **Lag Feature**

In [4]:
df['lag_1h'] = df['value'].shift(1)
df.head(10)

            timestamp      value  rolling_avg_24h  rolling_std_24h     lag_1h
0 2013-07-04 00:00:00  69.880835              NaN              NaN        NaN
1 2013-07-04 01:00:00  71.220227              NaN              NaN  69.880835
2 2013-07-04 02:00:00  70.877805              NaN              NaN  71.220227
3 2013-07-04 03:00:00  68.959400              NaN              NaN  70.877805
4 2013-07-04 04:00:00  69.283551              NaN              NaN  68.959400
5 2013-07-04 05:00:00  70.060966              NaN              NaN  69.283551
6 2013-07-04 06:00:00  69.279765              NaN              NaN  70.060966
7 2013-07-04 07:00:00  69.369608              NaN              NaN  69.279765
8 2013-07-04 08:00:00  69.166714              NaN              NaN  69.369608
9 2013-07-04 09:00:00  68.986083              NaN              NaN  69.166714

# **Difference Feature (Change from Last Hour)**

In [5]:
df['diff_1h'] = df['value'] - df['lag_1h']
df.head(10)

,timestamp,value,rolling_avg_24h,rolling_std_24h,lag_1h,diff_1h
0,2013-07-04 00:00:00,69.880835,NaN,NaN,NaN,NaN
1,2013-07-04 01:00:00,71.220227,NaN,NaN,69.880835,1.339392
2,2013-07-04 02:00:00,70.877805,NaN,NaN,71.220227,-0.342422
3,2013-07-04 03:00:00,68.959400,NaN,NaN,70.877805,-1.918405
4,2013-07-04 04:00:00,69.283551,NaN,NaN,68.959400,0.324151
5,2013-07-04 05:00:00,70.060966,NaN,NaN,69.283551,0.777415
6,2013-07-04 06:00:00,69.279765,NaN,NaN,70.060966,-0.781201
7,2013-07-04 07:00:00,69.369608,NaN,NaN,69.279765,0.089844
8,2013-07-04 08:00:00,69.166714,NaN,NaN,69.369608,-0.202895
9,2013-07-04 09:00:00,68.986083,NaN,NaN,69.166714,-0.180631

In [6]:
df_clean = df.dropna()
df_clean.shape

(7244, 6)

# **Processed Data Save Karo**

In [7]:
df_clean.to_csv("processed_temperature_data.csv", index=False)